# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

SECTION = "devel"
LICENSE = "Proprietary"
LIC_FILES_CHKSUM = "file://package.xml;md5=52cb6118c3330ae9cc1010de52a806f8"

DEPENDS = " \
        rclcpp \ 
        rclcpp-action \
        nav2-msgs \
        yaml-cpp \
        std-msgs \
        ament-cmake-native \
        ament-cmake-python \
        ament-cmake-ros-native \
        sensor-msgs \
        geometry-msgs \
        rosidl-adapter-native \
        rosidl-generator-py-native \
        rosidl-generator-c-native \
        rosidl-generator-cpp-native \
        rosidl-typesupport-cpp-native \
        rosidl-typesupport-fastrtps-c-native \
        rosidl-typesupport-fastrtps-cpp-native \
        ament-cmake-ros-native \
"

SRC_URI =  "file://econlidar.tar.bz2"
#SRCREV = "c0904f04a3db25091da82ead41ac6c131f9624cd"
S = "${WORKDIR}/econlidar"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}

FILES:${PN} += "\
  /usr/lib \
  /usr/share \
"
