# Generated by superflore -- DO NOT EDIT
#
# Copyright Open Source Robotics Foundation

inherit ros_distro_humble
inherit ros_superflore_generated

DESCRIPTION = "ROS2 package for ECON docking using ArUco markers"
SECTION = "devel"
LICENSE = "Proprietary"
LIC_FILES_CHKSUM = "file://package.xml;md5=81d23930a292050da11e42df10a572c0"

DEPENDS = " \
    rclcpp \
    rclcpp-action \
    geometry-msgs \
    nav-msgs \
    nav2-msgs \
    sensor-msgs \
    std-msgs \
    action-msgs \
    cv-bridge \
    opencv \
    tf2 \
    tf2-ros \
    builtin-interfaces \
    yaml-cpp \
    ament-cmake \
    ament-cmake-ros-native \
    ros2-katomaran-ros2base-interfaces \
"

# Update source path to match your package
SRC_URI = "file://econ_docking.tar.bz2"
S = "${WORKDIR}/econ_docking"

ROS_BUILD_TYPE = "ament_cmake"

inherit ros_${ROS_BUILD_TYPE}

FILES:${PN} += "\
  /usr/lib \
  /usr/share \
"
